module.exports = [
    {
        id: 'full_name',
        sortOrder: 1,
        prompt: '📝 *Escribe tu nombre completo*',
        fieldKey: 'full_name',
        inputType: 'text',
        validation: { required: true },
        nextQuestionId: 'age',
    },
    {
        id: 'age',
        sortOrder: 2,
        prompt: '🎂 *¿Cuál es tu edad?*',
        fieldKey: 'age',
        inputType: 'number',
        validation: { required: true, min: 1, max: 120 },
        nextQuestionId: 'max_weight',
    },
    {
        id: 'max_weight',
        sortOrder: 3,
        prompt: '📏 *¿Cuál ha sido tu peso máximo alcanzado?* (Especifica si son kilogramos o libras)',
        fieldKey: 'max_weight',
        inputType: 'text',
        validation: { required: true },
        nextQuestionId: 'current_weight',
    },
    {
        id: 'current_weight',
        sortOrder: 4,
        prompt: '⚖️ *¿Cuál es tu peso actual?* (Especifica si son kilogramos o libras)',
        fieldKey: 'current_weight',
        inputType: 'text',
        validation: { required: true },
        nextQuestionId: 'height_cm',
    },
    {
        id: 'height_cm',
        sortOrder: 5,
        prompt: '📐 *¿Cuál es tu estatura?* (En centímetros)',
        fieldKey: 'height_cm',
        inputType: 'number',
        validation: { required: true, min: 50, max: 260 },
        nextQuestionId: 'daily_routine',
    },
    {
        id: 'daily_routine',
        sortOrder: 6,
        prompt: '🕒 *Define tu rutina diaria* (Desde que te levantas hasta que te duermes)',
        fieldKey: 'daily_routine',
        inputType: 'textarea',
        validation: { required: true },
        nextQuestionId: 'does_exercise',
    },
    {
        id: 'does_exercise',
        sortOrder: 7,
        prompt: '🏃‍♂️ *¿Realizas alguna actividad física?* (Responde Sí o No)',
        fieldKey: 'does_exercise',
        inputType: 'choice',
        validation: { required: true, allowedValues: ['si', 'sí', 'no'] },
        branchMap: {
            si: 'training_time',
            sí: 'training_time',
            no: 'meals_per_day',
        },
    },
    {
        id: 'training_time',
        sortOrder: 8,
        prompt: '⏳ *¿Cuánto tiempo llevas entrenando?* (Especifica en meses o años)',
        fieldKey: 'training_time',
        inputType: 'text',
        validation: { required: true },
        nextQuestionId: 'training_type',
    },
    {
        id: 'training_type',
        sortOrder: 9,
        prompt: '🏋️‍♀️ *¿Qué tipo de entreno o actividad física realizas?*',
        fieldKey: 'training_type',
        inputType: 'text',
        validation: { required: true },
        nextQuestionId: 'training_frequency',
    },
    {
        id: 'training_frequency',
        sortOrder: 10,
        prompt: '📅 *¿Cuántas veces por semana lo realizas?*',
        fieldKey: 'training_frequency',
        inputType: 'number',
        validation: { required: true, min: 0, max: 14 },
        nextQuestionId: 'meals_per_day',
    },
    {
        id: 'meals_per_day',
        sortOrder: 11,
        prompt: '🍽️ *¿Cuántas comidas realizas al día?*',
        fieldKey: 'meals_per_day',
        inputType: 'number',
        validation: { required: true, min: 1, max: 12 },
        nextQuestionId: 'breakfast',
    },
    {
        id: 'breakfast',
        sortOrder: 12,
        prompt: '🍳 *¿Qué comes usualmente en el desayuno?*',
        fieldKey: 'breakfast',
        inputType: 'textarea',
        validation: { required: true },
        nextQuestionId: 'lunch',
    },
    {
        id: 'lunch',
        sortOrder: 13,
        prompt: '🥗 *¿Qué comes usualmente en el almuerzo?*',
        fieldKey: 'lunch',
        inputType: 'textarea',
        validation: { required: true },
        nextQuestionId: 'dinner',
    },
    {
        id: 'dinner',
        sortOrder: 14,
        prompt: '🍽️ *¿Qué comes usualmente en la cena?*',
        fieldKey: 'dinner',
        inputType: 'textarea',
        validation: { required: true },
        nextQuestionId: 'snacks',
    },
    {
        id: 'snacks',
        sortOrder: 15,
        prompt: '🍪 *Si haces snacks, especifica qué comes usualmente en ellos*',
        fieldKey: 'snacks',
        inputType: 'textarea',
        validation: { required: false },
        nextQuestionId: 'restricted_foods',
    },
    {
        id: 'restricted_foods',
        sortOrder: 16,
        prompt: '🚫 *Menciona los alimentos que no consumes ya sea por alergias o por preferencia*',
        fieldKey: 'restricted_foods',
        inputType: 'textarea',
        validation: { required: false },
        nextQuestionId: 'uses_supplements',
    },
    {
        id: 'uses_supplements',
        sortOrder: 17,
        prompt: '💊 *¿Has utilizado suplementos?* (Responde Sí o No)',
        fieldKey: 'uses_supplements',
        inputType: 'choice',
        validation: { required: true, allowedValues: ['si', 'sí', 'no'] },
        branchMap: {
            si: 'supplements_used',
            sí: 'supplements_used',
            no: 'medical_conditions',
        },
    },
    {
        id: 'supplements_used',
        sortOrder: 18,
        prompt: '📦 *¿Qué suplementos has utilizado?*',
        fieldKey: 'supplements_used',
        inputType: 'textarea',
        validation: { required: true },
        nextQuestionId: 'medical_conditions',
    },
    {
        id: 'medical_conditions',
        sortOrder: 19,
        prompt: '⚕️ *¿Tienes alguna patología especial?* (Especifica)',
        fieldKey: 'medical_conditions',
        inputType: 'textarea',
        validation: { required: false },
        nextQuestionId: 'goals',
    },
    {
        id: 'goals',
        sortOrder: 20,
        prompt: '🎯 *¿Cuáles son tus objetivos?* (Pérdida de peso, ganar masa muscular, etc.)',
        fieldKey: 'goals',
        inputType: 'textarea',
        validation: { required: true },
        nextQuestionId: 'country',
    },
    {
        id: 'country',
        sortOrder: 21,
        prompt: '🌍 *¿En qué país resides?*',
        fieldKey: 'country',
        inputType: 'text',
        validation: { required: true },
        nextQuestionId: null,
    },
];
